version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.15.0@sha256:03d14fbc5caa9f4e7760c840538a50cfd5f496cc099e625030ecdb30752ccdd8
    steps:
      - checkout
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test
      - store_artifacts:
          path: test-results.xml
          prefix: tests